Edited `man` for `blockCol`
waldronlab/lefser pull request #53
Opened 2024-08-04 02:19 UTC by asyakhl

Adding clarity/explanation to `man` for `blockCol`, explaining that this variable is usually two levels but can be more than two levels, and that `blockCol` argument is not a statistical blocking variable (`lefser` doesn't have a statistical blocking option).

2024-08-05 13:26 UTC, LiNk-NY requested changes

2024-08-05 13:26 UTC, LiNk-NY commented on man/lefser.Rd
Hi Asya! Can you edit the source R file? You can then run `devtools::document()` to update the Rd file.
https://github.com/waldronlab/lefser/blob/9dc5ac820137b2d826164c836cf75abdf1942966/R/lefser.R#L175

2024-08-11 21:36 UTC, asyakhl commented on man/lefser.Rd
Hi Marcel, I made some changes. Let me know anything else is required.

2024-08-12 13:50 UTC, LiNk-NY approved these changes

2024-08-16 13:47 UTC, merged