Deprecating groupCol and blockCol
waldronlab/lefser pull request #62
Opened 2024-09-14 21:31 UTC by asyakhl

Replacing  groupCol and blockCol  with classCol and subclassCol, and other group and block variable names. Also updated man files.

2024-09-14 23:38 UTC, shbrief commented
This pull request seems to include only the new argument names but doesn't have a deprecation process. I found this guide (https://contributions.bioconductor.org/deprecation.html) on function and dataset-level deprecations. @LiNk-NY Do you know whether there is a separate instruction on argument-level deprecations?

2024-09-16 18:31 UTC, LiNk-NY requested changes
- [x] Update the main `lefser` function to deprecate the arguments similar to the `expr` argument. 
- [x] Remove redundant text from documentation

2024-09-16 18:31 UTC, LiNk-NY commented on vignettes/lefser.Rmd
> +the two sample classes of interest, referred as ‘classes’. While *LEfSe* is
This is redundant

2024-09-16 18:31 UTC, LiNk-NY commented on R/lefser.R
> +    attr(res_scores, "blk") <- subclassCol
These attribute names should also change

2024-09-16 18:31 UTC, LiNk-NY commented on R/lefser.R
> +           subclassCol = NULL,
The lefser function shoul dkeep the `groupCol` and `blockCol` in the function signature. They should go after the `...` similarly to `expr`.

2024-09-16 18:32 UTC, LiNk-NY commented
ping @asyakhl

2024-09-17 14:33 UTC, LiNk-NY requested changes
Please update `lefsePlotFeat.R` to changes

2024-09-17 14:33 UTC, LiNk-NY commented on R/lefser.R
> +    attr(res_scores, "subclass") <- subclassCol
@asyakhl Were these updated in `lefsePlotFeat.R` ?

2024-09-23 17:06 UTC, LiNk-NY approved these changes
Thanks Asya! @asyakhl 
Other than the `man/lefserPlotFeat.Rd`, everything looks in order :) 
I think the merge commits got a little bit messy. 
For next time, use `rebase` often to pull changes from `devel` and to keep a linear history.

2024-09-24 02:14 UTC, shbrief commented on man/lefserPlotFeat.Rd
Oh... sorry, I was cleaning up to reflect the contributions in the repo and accidentally deleted that line. I'll put it back.

2024-09-24 02:15 UTC, shbrief commented on DESCRIPTION
> -  person("Ludwig", "Geistlinger", , "Ludwig.Geistlinger@sph.cuny.edu", "ctb", c(ORCID = "0000-0002-2495-5464")),
Sorry... I was cleaning up to reflect the contributions to the repo and accidentally deleted the line. I'll put it back.

2024-09-24 02:17 UTC, shbrief commented on man/lefserPlotFeat.Rd
Maybe incorporated during `rebase`?

2024-09-24 02:22 UTC, shbrief commented on R/lefserPlotFeat.R
> +#' plot_class <- lefsePlotFeat(res_class, res_class$features[[1]])
@asyakhl The correct function name is `lefserPlotFeat`, not `lefsePlotFeat`

2024-09-25 17:37 UTC, LiNk-NY commented
Thanks Asya! @asyakhl 
I squashed the commits and added a couple of changes at #65. I keep your authorship with `Co-authored-by: <...> `tag.

2024-09-25 17:41 UTC, closed without merging